import { spawnSync } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { afterEach, describe, expect, test } from "bun:test";

const tempDirs: string[] = [];

afterEach(async () => {
  while (tempDirs.length > 0) {
    const dir = tempDirs.pop();
    if (dir) {
      await rm(dir, { force: true, recursive: true });
    }
  }
});

describe("extract-privileged-contracts CLI", () => {
  // A stale generated contract left behind after descriptors are removed would
  // keep extracting (and approving) contracts the Space no longer defines.
  test("source generation removes stale generated contract when descriptors are removed", async () => {
    const dir = await mkdtemp(
      join(process.cwd(), ".tmp-privileged-contract-source-"),
    );
    tempDirs.push(dir);
    const sourcePath = join(dir, "privileged.ts");
    const generatedPath = join(dir, "privileged.contract.ts");
    await writeFile(
      sourcePath,
      `
        import { definePrivilegedHandlers } from "@hatch/space-sdk";
        export const privilegedHandlers = definePrivilegedHandlers({} as never, {});
      `,
      "utf8",
    );
    await writeFile(
      generatedPath,
      "// Generated by web_artifact_build from server/src/privileged.ts. Do not edit.\n",
      "utf8",
    );

    const result = spawnSync(
      process.execPath,
      [
        "src/extract-privileged-contracts-cli.ts",
        `--source=${sourcePath}`,
        `--generated-source-out=${generatedPath}`,
      ],
      {
        cwd: process.cwd(),
        encoding: "utf8",
      },
    );

    expect(result.status).toBe(0);
    expect(await Bun.file(generatedPath).exists()).toBe(false);
  });
});
