// Extract privileged function contracts from Space source/bundles.
//
// The build pipeline uses this runner for two related jobs:
// - Generate portable `server/.generated/privileged.contract.ts` source from the
//   author-owned `server/src/privileged.ts` descriptor block.
// - Extract metadata from the bundled portable contract module into
//   `server/dist/privileged-contracts.json`.

import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { pathToFileURL } from "node:url";

import { collectPrivilegedContracts } from "./privileged_contracts";

const GENERATED_HEADER =
  "// Generated by web_artifact_build from server/src/privileged.ts. Do not edit.";

function arg(name: string): string | undefined {
  const flag = `--${name}=`;
  for (const raw of process.argv.slice(2)) {
    if (raw.startsWith(flag)) {
      return raw.slice(flag.length);
    }
  }
  return undefined;
}

const modulePath = arg("module");
const outPath = arg("out");
const sourcePath = arg("source");
const generatedSourceOutPath = arg("generated-source-out");

if ((!modulePath || !outPath) && (!sourcePath || !generatedSourceOutPath)) {
  process.stderr.write(
    "usage: extract-privileged-contracts.js --module=<path> --out=<path> OR --source=<path> --generated-source-out=<path>\n",
  );
  process.exit(2);
}

const contractModulePath = modulePath;
const metadataOutPath = outPath;

async function main(): Promise<void> {
  if (sourcePath && generatedSourceOutPath) {
    const source = await readFile(sourcePath, "utf8");
    const generated = generatePrivilegedContractSource(source);
    if (generated === null) {
      await removeStaleGeneratedSource(generatedSourceOutPath);
      process.stdout.write(
        JSON.stringify({ ok: true, generated: false }) + "\n",
      );
      return;
    }
    await mkdir(dirname(generatedSourceOutPath), { recursive: true });
    await writeFile(generatedSourceOutPath, generated, "utf8");
    process.stdout.write(JSON.stringify({ ok: true, generated: true }) + "\n");
    return;
  }

  const moduleExports = (await import(
    pathToFileURL(contractModulePath!).href
  )) as Record<string, unknown>;
  const metadata = collectPrivilegedContracts(moduleExports);
  await writeFile(
    metadataOutPath!,
    JSON.stringify(metadata, null, 2) + "\n",
    "utf8",
  );
}

export function generatePrivilegedContractSource(source: string): string | null {
  const call = findDefinePrivilegedContractsCall(source);
  if (call === null) {
    return null;
  }
  return (
    `${GENERATED_HEADER}\n` +
    'import { definePrivilegedContracts, z } from "@hatch/space-sdk";\n\n' +
    `export const ${call.exportName} = definePrivilegedContracts(${call.argument});\n`
  );
}

async function removeStaleGeneratedSource(path: string): Promise<void> {
  const existing = await readFile(path, "utf8").catch(() => null);
  if (existing === null || !existing.startsWith(GENERATED_HEADER)) {
    return;
  }
  await unlink(path);
}

interface ContractCall {
  readonly exportName: string;
  readonly argument: string;
}

function findDefinePrivilegedContractsCall(source: string): ContractCall | null {
  const pattern =
    /\bexport\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*definePrivilegedContracts\s*\(/g;
  const match = pattern.exec(source);
  if (match === null) {
    return null;
  }
  const argumentStart = pattern.lastIndex;
  const argumentEnd = findMatchingCallArgumentEnd(source, argumentStart);
  if (argumentEnd === null) {
    throw new Error(
      `could not parse definePrivilegedContracts(...) for export '${match[1]}'`,
    );
  }
  return {
    exportName: match[1]!,
    argument: source.slice(argumentStart, argumentEnd).trim(),
  };
}

function findMatchingCallArgumentEnd(
  source: string,
  start: number,
): number | null {
  let parenDepth = 1;
  let braceDepth = 0;
  let bracketDepth = 0;
  let i = start;
  while (i < source.length) {
    const next = source[i + 1];
    const c = source[i]!;
    if (c === "/" && next === "/") {
      i += 2;
      while (i < source.length && source[i] !== "\n") i++;
      continue;
    }
    if (c === "/" && next === "*") {
      i += 2;
      while (
        i < source.length &&
        !(source[i] === "*" && source[i + 1] === "/")
      ) {
        i++;
      }
      i = Math.min(source.length, i + 2);
      continue;
    }
    if (c === "'" || c === '"') {
      i = skipQuoted(source, i, c);
      continue;
    }
    if (c === "`") {
      i = skipTemplate(source, i);
      continue;
    }
    if (c === "(") parenDepth++;
    if (c === ")") {
      parenDepth--;
      if (parenDepth === 0 && braceDepth === 0 && bracketDepth === 0) {
        return i;
      }
    }
    if (c === "{") braceDepth++;
    if (c === "}") braceDepth--;
    if (c === "[") bracketDepth++;
    if (c === "]") bracketDepth--;
    i++;
  }
  return null;
}

function skipQuoted(source: string, start: number, quote: string): number {
  let i = start + 1;
  while (i < source.length) {
    if (source[i] === "\\" && i + 1 < source.length) {
      i += 2;
      continue;
    }
    if (source[i] === quote) {
      return i + 1;
    }
    i++;
  }
  return source.length;
}

function skipTemplate(source: string, start: number): number {
  let i = start + 1;
  while (i < source.length) {
    if (source[i] === "\\" && i + 1 < source.length) {
      i += 2;
      continue;
    }
    if (source[i] === "`") {
      return i + 1;
    }
    i++;
  }
  return source.length;
}

main().catch((err) => {
  process.stderr.write(
    err instanceof Error ? `${err.message}\n` : `${String(err)}\n`,
  );
  process.exit(1);
});
